@ApiProjetos_HostAddress = http://localhost:5276

GET {{ApiProjetos_HostAddress}}/Projeto/GetAllPedidos
Accept: application/json

###

POST {{ApiProjetos_HostAddress}}/Projeto
content-type: application/json

{
    "Nome": "Projeto 1"
}

###

GET {{ApiProjetos_HostAddress}}/Projeto
Accept: application/json

###